# Generated by Django 5.1 on 2024-08-27 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='adress',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='ph',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.CreateModel(
            name='stuprofile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='web.student')),
            ],
        ),
    ]
