# Generated by Django 5.1 on 2024-08-28 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_student_adress_student_ph_alter_student_age_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('quant', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='stuprofile',
            name='student',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='stuprofile',
        ),
    ]
