# Generated by Django 5.1 on 2024-08-30 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_book_alter_item_quant'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='pub_year',
            field=models.IntegerField(default=0),
        ),
    ]
