# Generated by Django 5.1 on 2024-09-06 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='category',
        ),
        migrations.RemoveField(
            model_name='item',
            name='quant',
        ),
        migrations.AddField(
            model_name='item',
            name='doc',
            field=models.FileField(default=0, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='item',
            name='img',
            field=models.ImageField(default=0, upload_to='gallery/'),
        ),
    ]
